- |
        npm install -g eas-cli
        eas project:init --account nomadservice --non-interactive || true
        # Il flag --clear-cache pulisce i vecchi errori di Gradle
        eas build --platform android --profile preview --non-interactive --clear-cache
